root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/web"
  bin = "./tmp/main.exe"
  full_bin = ""

[build.env]
  GOPATH = "C:/Users/YourUsername/go"
  GOBIN = ""

[log]
  time = true
  color = true
  level = "debug"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true